In [3]:
!pip3 install numpy --upgrade

  Using cached https://files.pythonhosted.org/packages/03/27/e35e7c6e6a52fab9fcc64fc2b20c6b516eba930bb02b10ace3b38200d3ab/numpy-1.18.4-cp36-cp36m-manylinux1_x86_64.whl


In [4]:
import numpy as np

In [5]:
array_one = np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [6]:
numbers = [1,2,3,4]
array_two = np.array(numbers)
array_two

array([1, 2, 3, 4])

In [11]:
array_of_zeros = np.zeros([3,2])
array_of_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
array_of_ones = np.ones([3,2])
array_of_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
array_of_ones_int = np.ones([3,2], dtype=np.int16)
array_of_ones_int

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int16)

In [16]:
array_empty = np.empty([3,2])
array_empty

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
array_eye = np.eye(10)
array_eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
array_of_evens = np.arange(0,10,2)
array_of_evens

array([0, 2, 4, 6, 8])

In [21]:
array_of_odds = np.arange(1,10,2)
array_of_odds

array([1, 3, 5, 7, 9])

In [23]:
array_of_floats = np.arange(1, 10, 0.2)
array_of_floats

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [26]:
array_2d = np.array([(1,2,3), (4,5,6)])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
array_2d.shape

(2, 3)

In [28]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [30]:
array_reshape = np.arange(6).reshape(2,3)
array_reshape

array([[0, 1, 2],
       [3, 4, 5]])