In [1]:
import numpy as np

In [6]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [7]:
a + b

array([15, 15, 15])

In [8]:
a / b

array([2., 2., 2.])

In [9]:
a - b

array([5, 5, 5])

In [10]:
a * b

array([50, 50, 50])

In [11]:
a % 5

array([0, 0, 0])

In [12]:
a.dot(b)

150

In [13]:
a1 = np.array([[1,1], [0,1]])
b1 = np.array([[2,0], [3,4]])

In [14]:
a1 * b1

array([[2, 0],
       [0, 4]])

In [15]:
a1.dot(b1)

array([[5, 4],
       [3, 4]])

In [16]:
a < 32

array([ True,  True,  True])

In [17]:
a *= 3
a

array([30, 30, 30])

In [18]:
b += a
b

array([35, 35, 35])

In [19]:
array = np.array([10,45, 25,0])

In [20]:
array.sum()

80

In [21]:
array.max()

45

In [22]:
array.min()

0

In [23]:
numbers = np.arange(12).reshape(3,4)
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
numbers.sum(axis = 0)

array([12, 15, 18, 21])

In [25]:
numbers.sum(axis = 1)

array([ 6, 22, 38])